### ISSUE TITLE
Does CKAN allow definition of user groups who have access to certain data sets?

### ISSUE THREAD

**Issue by willu47** [ClimateCompatibleGrowth/ukpact_data_repository#5]
There are a number of sub-questions which need answering:

- Can viewing of data be restricted to authorised users?  E.g. is private data supported?
- Can users be assigned roles, which have certain permissions?  For example, could users be given a "data checking" role, which would allow them to read uploaded data, but not to edit it?
- Does CKAN support workflows where a sequence of steps happen after a dataset is uploaded?

**Comment by willu47** [comment]
- Does CKAN allow organisations to specify which other organisations can access datasets?
- Can this extended with only certain roles within organisations being allowed access.

**Comment by FrancisTembo** [comment]
CKAN employs role-based access control, allowing organizations to manage who can access their data effectively. Within each organization, there are three distinct user roles: 

1. **Administrator**: Has full control over all aspects of the organization’s data.  
2. **Editor**: Can edit resources and manage content within the organization.  
3. **Member**: Can view data but does not have permission to make any changes.  

An administrator can also add collaborators to a specific dataset.
